# AR5 Glaciers CMIP6-FAIR Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "ar5_preprocess_glaciersfair.py"
    options:
      - "scenario"
      - "baseyear"
      - "fullFAIR"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/ar5_preprocess_glaciersfair.py"
      - "%MODULE_PATH%/Smooth.py"
      - "%MODULE_PATH%/import_data.py"
      - "%MODULE_PATH%/filter_data.py"
    upload_and_extract_input_data:
      - "./modules-data/ar5_glaciersfair_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"

fit:
  task1:
    executable: "python3"
    script: "ar5_fit_glaciersfair.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ar5_fit_glaciersfair.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"

project:
  task1:
    executable: "python3"
    script: "ar5_project_glaciersfair.py"
    options:
      - "nmsamps"
      - "ntsamps"
      - "nsamps"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ar5_project_glaciersfair.py'
    upload_and_extract_input_data:
      - './modules-data/ar5_glaciersfair_project_data.tgz'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"


postprocess:
  task1:
    executable: "python3"
    script: "ar5_postprocess_glaciersfair.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ar5_postprocess_glaciersfair.py'
      - '%MODULE_PATH%/read_locationfile.py'
      - '%MODULE_PATH%/AssignFP.py'
      - '%MODULE_PATH%/ReadFingerprint.py'
    upload_and_extract_input_data:
      - './modules-data/ar5_glaciersfair_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
