# FACTS dummy pipeline

preprocess:
  task1:
    executable: "python"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib pandas xarray"
    script: "facts_dummy_preprocess.py"
    options:
      - "pipeline_id"
    #climate_output_data:
    #global_total_files:
    #local_total_files: