# Kopp14 Glaciers and Ice Caps Pipeline

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    python_dependencies: " numpy scipy netCDF4 pyyaml matplotlib"
    script: "kopp14_preprocess_glaciers.py"
    options:
      - "scenario"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/kopp14_preprocess_glaciers.py"
      - "%MODULE_PATH%/readMarzeion.py"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/data/kopp14_glaciers_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"
#      - "%PIPELINE_ID%_fp.pkl"
#      - "%PIPELINE_ID%_config.pkl"

fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "kopp14_fit_glaciers.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/kopp14_fit_glaciers.py'
      - '%MODULE_PATH%/cholcov.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
          - "%PIPELINE_ID%_config.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"

project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "kopp14_project_glaciers.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/kopp14_project_glaciers.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"


postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "kopp14_postprocess_glaciers.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/kopp14_postprocess_glaciers.py'
      - '%MODULE_PATH%/read_locationfile.py'
      - '%MODULE_PATH%/AssignFP.py'
      - '%MODULE_PATH%/ReadFingerprint.py'
    upload_and_extract_input_data:
      - '%MODULE_PATH%/data/kopp14_glaciers_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_fp.pkl"
          - "%PIPELINE_ID%_config.pkl"
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
