# AR5 Thermal Expansion Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "ipccar5_thermalexpansion_preprocess.py"
    options:
      - "scenario"
      - "baseyear"
      - "pipeline_id"
    upload_and_extract_input_data:
      - "ipccar5_climate_data.tgz"

fit:
  task1:
    executable: "python3"
    script: "ipccar5_thermalexpansion_fit.py"
    options:
      - "pipeline_id"

project:
  task1:
    executable: "python3"
    script: "ipccar5_thermalexpansion_project.py"
    options:
      - "nsamps"
      - "seed"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"


postprocess:
  task1:
    executable: "python3"
    script: "ipccar5_thermalexpansion_postprocess.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - 'read_locationfile.py'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
