# AR5 Thermal Expansion Pipeline

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "ar5_preprocess_thermalexpansion.py"
    options:
      - "scenario"
      - "baseyear"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/ar5_preprocess_thermalexpansion.py"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/data/ar5_thermalexpansion_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"

fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "ar5_fit_thermalexpansion.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ar5_fit_thermalexpansion.py'
#    copy_input_data:
#      preprocess:
#        task1:
#          - "%PIPELINE_ID%_data.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"

project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "ar5_project_thermalexpansion.py"
    options:
      - "nsamps"
      - "seed"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ar5_project_thermalexpansion.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"


postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "ar5_postprocess_thermalexpansion.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ar5_postprocess_thermalexpansion.py'
      - '%MODULE_PATH%/read_locationfile.py'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
