# ISMIP Emulated Ice Sheets Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "ipccar6_ismipemuicesheet_preprocess.py"
    options:
      - "scenario"
      - "model_driver"
      - "baseyear"
      - "pipeline_id"
    upload_input_data:
      - "import_data.py"
      - "filter_data.py"
      - "FindFAIRInputSamples.py"
      - "import_temp_data.py"
      - "filter_temp_data.py"
      - "Smooth.py"
    upload_and_extract_input_data:
      - "ipccar6_ismipemuicesheet_preprocess_data.tgz"


fit:
  task1:
    executable: "python3"
    script: "ipccar6_ismipemuicesheet_fit.py"
    options:
      - "pipeline_id"

project:
  task1:
    executable: "python3"
    script: "ipccar6_ismipemuicesheet_project.py"
    options:
      - "nsamps"
      - "replace"
      - "seed"
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    global_total_files:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_PEN_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    script: "ipccar6_ismipemuicesheet_postprocess.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - 'read_locationfile.py'
      - 'AssignFP.py'
      - 'ReadFingerprint.py'
    upload_and_extract_input_data:
      - 'grd_fingerprints_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_AIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
