# Kopp14 Sterodynamics Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml h5py"
    script: "kopp14_oceandynamics_preprocess.py"
    options:
      - "scenario"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - "IncludeModels.py"
      - "IncludeDABZOSModels.py"
      - "SmoothZOSTOGA.py"
      - "DriftCorr.py"
      - "Smooth.py"
      - "read_locationfile.py"
      - "read_CSIRO.py"
      - "readMarzeion.py"
    upload_and_extract_input_data:
      - "kopp14_sterodynamics_data.tgz"
    copy_shared_data:
      - '$SHARED/location.lst'
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"


fit:
  task1:
    executable: "python3"
    script: "kopp14_oceandynamics_fit.py"
    options:
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOSTOGA.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"

project:
  task1:
    executable: "python3"
    script: "kopp14_oceandynamics_project.py"
    options:
      - "pipeline_id"
      - "nsamps"
      - "seed"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    script: "kopp14_oceandynamics_postprocess.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
          - "%PIPELINE_ID%_oceandynamics_fit.pkl"
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
