global-options:
    nsamps: 20000
    scenario: ssp585
    pyear_start: 2020
    pyear_end: 2150
    pyear_step: 10
    baseyear: 2005
    rcfg-name: "amarel"

climate_step:
    temperature:
        module_set: "fair"
        module: "temperature"
        generates_climate_output: true
#        input_data_file:
#              - "emissions.csv"
#        options:
#              rcmip_file: emissions.csv

sealevel_step:
    larmip:
        module_set: "larmip"
        module: "AIS"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"