# SSP Land water storage pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "ssp_preprocess_landwaterstorage.py"
    options:
      - "scenario"
      - "dotriangular"
      - "includepokherl"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/ssp_preprocess_landwaterstorage.py"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/data/ssp_landwaterstorage_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"
#      - "%PIPELINE_ID%_config.pkl"

fit:
  task1:
    executable: "python3"
    script: "ssp_fit_landwaterstorage.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ssp_fit_landwaterstorage.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
          - "%PIPELINE_ID%_config.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"

project:
  task1:
    executable: "python3"
    script: "ssp_project_landwaterstorage.py"
    options:
      - "pipeline_id"
      - "nsamps"
      - "dcyear_start"
      - "dcyear_end"
      - "dcrate_lo"
      - "dcrate_hi"
      - "seed"
    upload_input_data:
      - '%MODULE_PATH%/ssp_project_landwaterstorage.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python3"
    script: "ssp_postprocess_landwaterstorage.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ssp_postprocess_landwaterstorage.py'
      - '%MODULE_PATH%/read_locationfile.py'
      - '%MODULE_PATH%/AssignFP.py'
    upload_and_extract_input_data:
      - '%MODULE_PATH%/data/ssp_landwaterstorage_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"