# SSP Land water storage pipeline

pre-process:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ssp_landwaterstorage_data.tgz; pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml matplotlib"
    script: "ssp_preprocess_landwaterstorage.py"
    options:
      - "scenario"
      - "dotriangular"
      - "includepokherl"
      - "pipeline_id"
    upload_input_data:
      - "./modules/ssp/landwaterstorage/ssp_preprocess_landwaterstorage.py"
      - "./modules/ssp/landwaterstorage/data/ssp_landwaterstorage_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"
#      - "%PIPELINE_ID%_config.pkl"

fit:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "ssp_fit_landwaterstorage.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/ssp/landwaterstorage/ssp_fit_landwaterstorage.py'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_data.pkl"
          - "%PIPELINE_ID%_config.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"

project:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "ssp_project_landwaterstorage.py"
    options:
      - "pipeline_id"
      - "nsamps"
      - "seed"
    upload_input_data:
      - './modules/ssp/landwaterstorage/ssp_project_landwaterstorage.py'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    download_output_data:
      - "%PIPELINE_ID%_projections.pkl"
