# emulandice GrIS Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib xarray dask"
    script_noupload: "emulandice_preprocess.py"
    arguments:
      - "--input_data_file"
      - "%CLIMATE_GSAT_FILE%"
    options:
      - "baseyear"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/../shared/emulandice_preprocess.py"
      - "%MODULE_PATH%/../shared/FACTS_CLIMATE_FORCING.csv.head"


fit:
  task1:
    executable: "python3"
    script: "emulandice_GrIS_fit.py"
    options:
      - "pipeline_id"


project:
  task1:
    executable: "python3"
    script: "emulandice_GrIS_project.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/../shared/emulandice_environment.sh"
      - "%MODULE_PATH%/../shared/emulandice_steer.sh"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/../shared/emulandice_bundled_dependencies.tgz"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_preprocess.pkl"
          - "FACTS_CLIMATE_FORCING.csv"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    script: "emulandice_GrIS_postprocess.py"
    options:
      - "locationfile"
      - "chunksize"
      - "pipeline_id"
    upload_input_data:
      - 'read_locationfile.py'
      - 'AssignFP.py'
      - 'ReadFingerprint.py'
    upload_and_extract_input_data:
      - 'grd_fingerprints_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
