# this script sets up the R environment from scratch 

r = getOption("repos") 
r["CRAN"] = "https://cloud.r-project.org"
options(repos = r)

install.packages('packrat')
packrat::init(infer.dependencies=FALSE)
packrat::set_opts(local.repos = c("/projects/community/R3.6_lib_workshop","."))
packrat::install_local('dummies_1.5.6.tar.gz')
packrat::install_local('cli')
packrat::install_local('colorspace')
packrat::install_local('ellipsis')
packrat::install_local('magrittr')
packrat::install_local('pillar')
packrat::install_local('fansi')
packrat::install_local('utf8')
packrat::install_local('pkgconfig')
packrat::install_local('tidyselect')
packrat::install_local('tzdb')
packrat::install_local('stringi')
packrat::install_local('stringr')
packrat::install_local('hms')
packrat::install_local('glue')
packrat::install_local('grDevices')
packrat::install_local('grid')
packrat::install_local('gtable')
packrat::install_local('isoband')
packrat::install_local('mgcv')
packrat::install_local('stats')
packrat::install_local('vctrs')
packrat::install_local('withr')
packrat::install_local('rlang')
packrat::install_local('scales')
packrat::install_local('lifecycle')
packrat::install_local('munsell')
packrat::install_local('colorspace')
packrat::install_local('ggplot2')
packrat::install_local('dplyr')
packrat::install_local('tidyr')
packrat::install_local('readr')
packrat::install_local('purrr')
packrat::install_local('tibble')
packrat::install_local('stringr')
packrat::install_local('forcats')
packrat::install_local('DiceKriging')
packrat::install_local('MASS')
packrat::install_local('Rcpp')
packrat::install_local('RcppEigen')
packrat::install_local('nloptr')
install.packages('RobustGaSP')
install.packages('DiceEval')
packrat::snapshot()
