# NZ Insar GPS Vertical Land Motion Pipeline

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    python_dependencies: "numpy scipy netCDF4 pyyaml"
    script: "NZInsarGPS_preprocess_verticallandmotion.py"
    options:
      - "pipeline_id"
      - "inputtype"
    upload_input_data:
      - "%MODULE_PATH%/NZInsarGPS_preprocess_verticallandmotion.py"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/data/NZInsarGPS_verticallandmotion_preprocess.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "NZInsarGPS_fit_verticallandmotion.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/NZInsarGPS_fit_verticallandmotion.py'


project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "NZInsarGPS_project_verticallandmotion.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/NZInsarGPS_project_verticallandmotion.py'

postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "NZInsarGPS_postprocess_verticallandmotion.py"
    options:
      - "nsamps"
      - "seed"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/NZInsarGPS_postprocess_verticallandmotion.py'
      - '%MODULE_PATH%/read_locationfile.py'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
