# Kopp14 Ice Sheets Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "kopp14_icesheets_preprocess.py"
    options:
      - "scenario"
      - "srocc"
      - "pipeline_id"


fit:
  task1:
    executable: "python3"
    script: "kopp14_icesheets_fit.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - 'CalcISDists.py'
      - 'FitLNDistQuants.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_rates.pkl"


project:
  task1:
    executable: "python3"
    script: "kopp14_icesheets_project.py"
    options:
      - "nsamps"
      - "seed"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "pipeline_id"
    upload_input_data:
      - 'SampleISDists.py'
      - 'cholcov.py'
      - 'ProjectGSL.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_corr.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"


postprocess:
  task1:
    executable: "python3"
    script: "kopp14_icesheets_postprocess.py"
    options:
      - "samp_type"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - 'SampleISDists.py'
      - 'read_locationfile.py'
      - 'AssignFP.py'
      - 'ReadFingerprint.py'
    upload_and_extract_input_data:
      - 'grd_fingerprints_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
