# LARMIP2 Ice Sheet Pipeline

preprocess:
  task1:
    executable: "python"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib h5py"
    script: "larmip_preprocess_icesheet.py"
    options:
      - "scenario"
      - "pipeline_id"
      - "climate_data_file"
    upload_input_data:
      - "%MODULE_PATH%/larmip_preprocess_icesheet.py"
    upload_and_extract_input_data:
      - "./modules-data/ipccar6_climate_data.tgz"


fit:
  task1:
    executable: "python"
    script: "larmip_fit_icesheet.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/larmip_fit_icesheet.py'
    upload_and_extract_input_data:
      - './modules-data/larmip_icesheet_fit_data.tgz'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_preprocess.pkl"


project:
  task1:
    executable: "python"
    script: "larmip_project_icesheet.py"
    options:
      - "nsamps"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "seed"
      - "models"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/larmip_project_icesheet.py'
    upload_and_extract_input_data:
      - './modules-data/larmip_icesheet_project_data.tgz'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_preprocess.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
          - "%PIPELINE_ID%_fitsmb.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_SMB_globalsl.nc"
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_PEN_globalsl.nc"
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python"
    script: "larmip_postprocess_icesheet.py"
    options:
      - "locationfile"
      - "chunksize"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/larmip_postprocess_icesheet.py'
      - '%MODULE_PATH%/read_locationfile.py'
      - '%MODULE_PATH%/AssignFP.py'
      - '%MODULE_PATH%/ReadFingerprint.py'
    upload_and_extract_input_data:
      - './modules-data/larmip_icesheet_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
      - "%PIPELINE_ID%_localsl.nc"
