# Generic Module 'Direct Sample' pipeline

preprocess:
  task1:
    executable: "python"
    pre_exec: "pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml matplotlib"
    script: "genmod_preprocess_directsample.py"
    experiment_input_data_file
    options:
      - "input_data_file"
      - "pipeline_id"

project:
  task1:
    executable: "python"
    pre_exec: []
    script: "genmod_project_directsample.py"
    options:
      - "nsamps"
      - "pipeline_id"
      - "replace"
      - "seed"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    download_output_data:
      - "%PIPELINE_ID%_projections.pkl"
