# Generic Module 'Direct Sample' pipeline

preprocess:
  task1:
    executable: "python"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "genmod_directsample_preprocess.py"
    experiment_input_data_file
    options:
      - "input_data_file"
      - "pipeline_id"

project:
  task1:
    executable: "python"
    pre_exec: []
    script: "genmod_directsample_project.py"
    options:
      - "nsamps"
      - "pipeline_id"
      - "replace"
      - "seed"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    download_output_data:
      - "%PIPELINE_ID%_projections.pkl"
