# Kopp14 Ocean Dynamics Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml h5py"
    script: "kopp14_preprocess_oceandynamics.py"
    options:
      - "scenario"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/kopp14_preprocess_oceandynamics.py"
      - "%MODULE_PATH%/IncludeModels.py"
      - "%MODULE_PATH%/IncludeDABZOSModels.py"
      - "%MODULE_PATH%/SmoothZOSTOGA.py"
      - "%MODULE_PATH%/DriftCorr.py"
      - "%MODULE_PATH%/Smooth.py"
      - "%MODULE_PATH%/read_locationfile.py"
      - "%MODULE_PATH%/read_CSIRO.py"
      - "%MODULE_PATH%/readMarzeion.py"
    upload_and_extract_input_data:
      - "./modules-data/kopp14_oceandynamics_data.tgz"
    copy_shared_data:
      - '$SHARED/location.lst'
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"


fit:
  task1:
    executable: "python3"
    script: "kopp14_fit_oceandynamics.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/kopp14_fit_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOSTOGA.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"

project:
  task1:
    executable: "python3"
    script: "kopp14_project_oceandynamics.py"
    options:
      - "pipeline_id"
      - "nsamps"
      - "seed"
    upload_input_data:
      - '%MODULE_PATH%/kopp14_project_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    script: "kopp14_postprocess_oceandynamics.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/kopp14_postprocess_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
          - "%PIPELINE_ID%_oceandynamics_fit.pkl"
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
