# DeConto et al 2021 Ice Sheets Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib xarray dask"
    script: "dp21_preprocess_icesheet.py"
    options:
      - "scenario"
      - "pipeline_id"
      - "baseyear"
    upload_input_data:
      - "%MODULE_PATH%/dp21_preprocess_icesheet.py"
    upload_and_extract_input_data:
      - "./modules-data/dp21_icesheet_preprocess_data.tgz"


fit:
  task1:
    executable: "python3"
    pre_exec: []
    script: "dp21_fit_icesheet.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/dp21_fit_icesheet.py'


project:
  task1:
    executable: "python3"
    script: "dp21_project_icesheet.py"
    options:
      - "nsamps"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "seed"
      - "replace"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/dp21_project_icesheet.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    global_total_files:
      - "%PIPELINE_ID%_AIS_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python3"
    script: "dp21_postprocess_icesheet.py"
    options:
      - "chunksize"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/dp21_postprocess_icesheet.py'
      - '%MODULE_PATH%/read_locationfile.py'
      - '%MODULE_PATH%/AssignFP.py'
      - '%MODULE_PATH%/ReadFingerprint.py'
    upload_and_extract_input_data:
      - './modules-data/dp21_icesheet_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_AIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_AIS_localsl.nc"
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
