# DeConto et al 2021 Ice Sheets Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib xarray dask"
    script: "deconto21_AIS_preprocess.py"
    options:
      - "scenario"
      - "pipeline_id"
      - "baseyear"
    upload_and_extract_input_data:
      - "deconto21_AIS_preprocess_data.tgz"


fit:
  task1:
    executable: "python3"
    pre_exec: []
    script: "deconto21_AIS_fit.py"
    options:
      - "pipeline_id"

project:
  task1:
    executable: "python3"
    script: "deconto21_AIS_project.py"
    options:
      - "nsamps"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "seed"
      - "replace"
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    global_total_files:
      - "%PIPELINE_ID%_AIS_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    script: "deconto21_AIS_postprocess.py"
    options:
      - "chunksize"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - 'read_locationfile.py'
      - 'AssignFP.py'
      - 'ReadFingerprint.py'
    upload_and_extract_input_data:
      - 'grd_fingerprints_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_AIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
