# FAIR temperature pipeline configuration

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib pandas xarray dask fair"
    script: "fair_preprocess_temperature.py"
    options:
      - "scenario"
      - "rcmip_file"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/fair_preprocess_temperature.py"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/data/fair_temperature_preprocess_data.tgz"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "fair_fit_temperature.py"
    options:
      - "param_file"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/fair_fit_temperature.py"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/data/fair_temperature_fit_data.tgz"



project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "fair_project_temperature.py"
    options:
      - "pipeline_id"
      - "nsamps"
      - "seed"
      - "cyear_start"
      - "cyear_end"
      - "smooth_win"
    upload_input_data:
      - "%MODULE_PATH%/fair_project_temperature.py"
      - "%MODULE_PATH%/my_FAIR_forward.py"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_preprocess.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    climate_output_data:
      - "%PIPELINE_ID%_oceantemp.nc"
      - "%PIPELINE_ID%_ohc.nc"
      - "%PIPELINE_ID%_gsat.nc"
      - "%PIPELINE_ID%_climate.nc"
    download_output_data:
      - "%PIPELINE_ID%_oceantemp.nc"
      - "%PIPELINE_ID%_ohc.nc"
      - "%PIPELINE_ID%_gsat.nc"
      - "%PIPELINE_ID%_climate.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "fair_postprocess_temperature.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/fair_postprocess_temperature.py'
