# Two-layer Model Ocean Dynamics Pipeline
# modified from the Kopp14 pipeline.yml, needs  to be examined

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml h5py"
    script: "tlm_preprocess_oceandynamics.py"
    options:
      - "scenario"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "pipeline_id"
      - "model_dir"
      - "no_drift_corr"
      - "no_correlation"
      - "climate_data_file"
    upload_input_data:
      - "%MODULE_PATH%/tlm_preprocess_oceandynamics.py"
      - "%MODULE_PATH%/Import2lmData.py"
      - "%MODULE_PATH%/IncludeCMIP6Models.py"
      - "%MODULE_PATH%/IncludeCMIP6ZOSModels.py"
      - "%MODULE_PATH%/SmoothZOSTOGA.py"
      - "%MODULE_PATH%/Smooth.py"
      - "%MODULE_PATH%/read_locationfile.py"
      - "%MODULE_PATH%/read_CSIRO.py"
      - "%MODULE_PATH%/readMarzeion.py"
    upload_and_extract_input_data:
      - "./modules-data/tlm_oceandynamics_preprocess.tgz"
      - "./modules-data/tlm_oceandynamics_cmip6.tgz"
      - "./modules-data/ipccar6_climate_data.tgz"
    copy_shared_data:
      - '$SHARED/location.lst'
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"


fit:
  task1:
    executable: "python3"
    script: "tlm_fit_oceandynamics.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/tlm_fit_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOSTOGA.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"
          - "%PIPELINE_ID%_tlmdata.pkl"

project:
  task1:
    executable: "python3"
    script: "tlm_project_oceandynamics.py"
    options:
      - "pipeline_id"
      - "nsamps"
      - "seed"
      - "tlm"
    upload_input_data:
      - '%MODULE_PATH%/tlm_project_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOSTOGA.pkl"
          - "%PIPELINE_ID%_tlmdata.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
          - "%PIPELINE_ID%_tlmfit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    script: "tlm_postprocess_oceandynamics.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
      - "chunksize"
      - "keep_temp"
    upload_input_data:
      - '%MODULE_PATH%/tlm_postprocess_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
          - "%PIPELINE_ID%_oceandynamics_fit.pkl"
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
