# IPCCAR6 Larmip Ice Sheets Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib h5py"
    script: "ipccar6_preprocess_larmipicesheet.py"
    options:
      - "scenario"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "pipeline_id"
      - "tlm_data"
    upload_input_data:
      - "Import2lmData.py"
    upload_and_extract_input_data:
      - "ipccar6_larmipAIS_preprocess_data.tgz"
      - "ipccar6_larmipAIS_preprocess_data_2lm.tgz"


fit:
  task1:
    executable: "python3"
    script: "ipccar6_fit_larmipicesheet.py"
    options:
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_smbdata.pkl"


project:
  task1:
    executable: "python3"
    script: "ipccar6_project_larmipicesheet.py"
    options:
      - "nsamps"
      - "seed"
      - "replace"
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
          - "%PIPELINE_ID%_smbdata.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_TOT_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_SMB_globalsl.nc"
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_PEN_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    script: "ipccar6_postprocess_larmipicesheet.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - 'read_locationfile.py'
      - 'AssignFP.py'
      - 'ReadFingerprint.py'
    upload_and_extract_input_data:
      - 'grd_fingerprints_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_AIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
