# emulandice glaciers Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "emulandice_preprocess.py"
    arguments:
      - "--input_data_file"
      - "%CLIMATE_GSAT_FILE%"
    options:
      - "baseyear"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/../shared/emulandice_preprocess.py"
      - "%MODULE_PATH%/../shared/FACTS_CLIMATE_FORCING.csv.head"


fit:
  task1:
    executable: "python3"
    script: "emulandice_fit_glaciers.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/emulandice_fit_glaciers.py"



project:
  task1:
    executable: "python3"
    script: "emulandice_project_glaciers.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/emulandice_project_glaciers.py"
      - "%MODULE_PATH%/../shared/emulandice_environment.sh"
      - "%MODULE_PATH%/../shared/emulandice_1.1.0.tar.gz"
      - "%MODULE_PATH%/../shared/emulandice_steer.sh"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/../shared/emulandice_bundled_dependencies.tgz"
#    pre_exec: "source ${RP_TASK_SANDBOX}/emulandice_environment.sh --Rscript"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_preprocess.pkl"
          - "FACTS_CLIMATE_FORCING.csv"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python3"
    script: "emulandice_postprocess_glaciers.py"
    options:
      - "locationfile"
      - "chunksize"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/emulandice_postprocess_glaciers.py'
      - '%MODULE_PATH%/read_locationfile.py'
      - '%MODULE_PATH%/AssignFP.py'
      - '%MODULE_PATH%/ReadFingerprint.py'
    upload_and_extract_input_data:
      - './modules-data/emulandice_glaciers_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
