# Kopp14 Land water storage pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "kopp14_landwaterstorage_preprocess.py"
    options:
      - "dotriangular"
      - "includepokherl"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "pipeline_id"
    upload_and_extract_input_data:
      - "kopp14_landwaterstorage_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"
#      - "%PIPELINE_ID%_config.pkl"

fit:
  task1:
    executable: "python3"
    script: "kopp14_landwaterstorage_fit.py"
    options:
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
          - "%PIPELINE_ID%_config.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"

project:
  task1:
    executable: "python3"
    script: "kopp14_landwaterstorage_project.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"


postprocess:
  task1:
    executable: "python3"
    script: "kopp14_landwaterstorage_postprocess.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - 'read_locationfile.py'
#      - 'kopp14_landwaterstorage_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
