# Two-layer Model Ocean Dynamics Pipeline
# modified from the Kopp14 pipeline.yml, needs  to be examined

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml h5py"
    script: "tlm_sterodynamics_preprocess_thermalexpansion.py"
    options:
      - "scenario"
      - "climate_data_file"
      - "pipeline_id"
    upload_input_data:
      - "Import2lmData.py"
    upload_and_extract_input_data:
      - "tlm_sterodynamics_preprocess_data.tgz"
  task2:
    executable: "python3"
    script: "tlm_sterodynamics_preprocess_oceandynamics.py"
    options:
      - "scenario"
      - "scenario_dsl"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "pipeline_id"
      - "model_dir"
      - "no_drift_corr"
      - "no_correlation"
    upload_input_data:
      - "IncludeCMIP6Models.py"
      - "IncludeCMIP6ZOSModels.py"
      - "SmoothZOSTOGA.py"
      - "Smooth.py"
      - "read_locationfile.py"
    upload_and_extract_input_data:
      - "tlm_sterodynamics_cmip6_data.tgz"
    copy_shared_data:
      - '$SHARED/location.lst'

fit:
  task1:
    executable: "python3"
    script: "tlm_sterodynamics_fit_thermalexpansion.py"
    options:
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_tlmdata.pkl"
  task2:
    executable: "python3"
    script: "tlm_sterodynamics_fit_oceandynamics.py"
    options:
      - "pipeline_id"
    copy_input_data:
      preprocess:
        task2:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOSTOGA.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"

project:
  task1:
    executable: "python3"
    script: "tlm_sterodynamics_project.py"
    options:
      - "pipeline_id"
      - "nsamps"
      - "seed"
      - "scenario"
      - "scenario_dsl"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_tlmdata.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_tlmfit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    script: "tlm_sterodynamics_postprocess.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
      - "chunksize"
      - "keep_temp"
    copy_input_data:
      preprocess:
        task2:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"
      fit:
        task2:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
          - "%PIPELINE_ID%_oceandynamics_fit.pkl"
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_OceanDyn.nc"
