# AR5 Ice Sheets Pipeline

preprocess:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib"
    script: "ar5_preprocess_icesheets.py"
    options:
      - "scenario"
      - "pipeline_id"
      - "baseyear"
      - "tlm_data"
      - "climate_data_file"
    upload_input_data:
      - "%MODULE_PATH%/ar5_preprocess_icesheets.py"
      - "%MODULE_PATH%/Import2lmData.py"
    upload_and_extract_input_data:
      - "./modules-data/ar5_icesheets_preprocess_data.tgz"
      - "./modules-data/ipccar6_climate_data.tgz"



fit:
  task1:
    executable: "python3"
    script: "ar5_fit_icesheets.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ar5_fit_icesheets.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"


project:
  task1:
    executable: "python3"
    script: "ar5_project_icesheets.py"
    options:
      - "nmsamps"
      - "ntsamps"
      - "nsamps"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ar5_project_icesheets.py'
    upload_and_extract_input_data:
      - './modules-data/ar5_icesheets_project_data.tgz'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_TIS_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
      - "%PIPELINE_ID%_TIS_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python3"
    script: "ar5_postprocess_icesheets.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ar5_postprocess_icesheets.py'
      - '%MODULE_PATH%/read_locationfile.py'
      - '%MODULE_PATH%/AssignFP.py'
      - '%MODULE_PATH%/ReadFingerprint.py'
    upload_and_extract_input_data:
      - './modules-data/ar5_icesheets_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
          - "%PIPELINE_ID%_data.pkl"          
    local_total_files:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
